# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dhruv's Bog
tagline:          Always Be Learnin'
url:              http://dhruvp.github.io
paginate:         1
baseurl:          /
author:
  name:           Dhruv Parthasarathy
  email:          dhruv@udacity.com

# Custom vars
version:          1.0.0
github:           https://github.com/dhruvp
